### ISSUE TITLE
[feat]: add ability to use different images for jobs in specific build

### ISSUE THREAD

**Issue by jkuri** [bleenco/abstruse#292]
we need to add functionality that allow usage of different docker images in build matrix.
when adding this, it is important that all configurations are backward compatible.
the build matrix at this moment is defined as
```yaml
image: abstruse_node

matrix:
  - env: SCRIPT=lint NODE_VERSION=8
  - env: SCRIPT=test NODE_VERSION=8
  - env: SCRIPT=test:e2e NODE_VERSION=8
  - env: SCRIPT=test:protractor NODE_VERSION=8
  - env: SCRIPT=test:karma NODE_VERSION=8

...
```

which should still work in the future.

proposal for new style that allows specific images:
```yaml
image: abstruse_node

matrix:
  - image: abstruse-armhf-cpp
    env: TASK=build COMPILER=clang++
  - image: abstruse-amd64-cpp
    env: TASK=build COMPILER=g++
  - env: SCRIPT=test NODE_VERSION=8
```
where image is not strictly specified (last job in matrix), default image specified globally on top is used.
