### ISSUE TITLE
abstruse 1.4.0 deploy fail

### ISSUE THREAD

**Issue by elthariel** [bleenco/abstruse#304]
I'm sorry, this bug report kinda sucks but I've almost no understanding of the whole node stack, so I haven't been able to dig to provide a better report.

Using the last release, the `deploy` block with a single string or an array of commands fails with a very obscure error in the logs along the line of: `[error]: [Object object]`.

Here's the .abstruse.yml:

```yaml
image: node_builder

matrix:
  - env: NODE_VERSION=8

before_install:
  - nvm install ${NODE_VERSION:-8}
  - npm config set spin false
  - npm config set progress false

install:
  - npm install

script:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi

deploy:
  - ./deploy.sh

cache:
  - node_modules
```
