### ISSUE TITLE
Comparison to Drone CI?

### ISSUE THREAD

**Issue by Rush** [bleenco/abstruse#344]
Hello, very interesting project. Any idea on how does it compare to Drone CI? At my company we're successfully using Drone CI which is also open source, docker based and written in Go.

I am glad to see some competition as it is always good for the end user.

**Comment by irmana** [comment]
@Rush thanks! When there is a difference in performance, it should be hardly noticeable. Guys at Drone did a great job.
Perhaps our biggest difference is the community size (NodeJS is more popular than Golang atm) which may be advantageous down the road on getting popularity. Maybe there is some difference in features and UX. Can you can comment on that?

**Comment by Rush** [comment]
What's most interesting to me is the feature set of the build definition files. Drone has capability to do parallel pipeline builds, it has support for services (mongo, postgres), it has plugins for caching (for example cache for `npm install`), it has capability dor running docker in docker.

One of the use cases for docker in docker is ability to build the very image you're going to use for the build itself. For example:
```
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
  docker:
    image: docker
    commands:
      - docker build -t ps-ci-image:${DRONE_COMMIT_SHA} ./docker/drone-ci
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  install:
    image: ps-ci-image:${DRONE_COMMIT_SHA}
    environment:
      - JOBS=8
    commands:
      - npm install --quiet
  test_server:
    image: ps-ci-image:${DRONE_COMMIT_SHA}
    group: testing
    commands:
      - npm run test:server
  rebuild-cache:                                                                                                                                                                                                                                             
    image: drillster/drone-volume-cache                                                                                                                                                                                                                      
    rebuild: true                                                                                                                                                                                                                                            
    mount:                                                                                                                                                                                                                                                   
      - ./node_modules                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    volumes:                                                                                                                                                                                                                                                 
      - /tmp/cache:/cache
```
