### ISSUE TITLE
Job never gets created

### ISSUE THREAD

**Issue by ForsakenHarmony** [bleenco/abstruse#401]
I don't know what I'm doing wrong, tried to follow the guide, first I didn't have a custom image, which I have now, but when a build gets created no build ever starts, don't get any errors in the logs either

I have: base image, custom image build on top called "base_nvm"

.abstruse.yml
```yml
image: "base_nvm"

install:
  - echo "install"

before_script:
  - echo "before"
script:
  - echo "test"
  - cat README.md
  - exit 1
```

![image](https://user-images.githubusercontent.com/8845940/44546140-56f84e00-a717-11e8-98f7-3f3f3a301614.png)

The timer never goes up or anything, have been trying to get it to work for ~2 hrs now
