### ISSUE TITLE
Builds not getting built but instantly marked as successful

### ISSUE THREAD

**Issue by aarivex** [bleenco/abstruse#447]
I'm using abstruse for the first time and I pretty much love it, i'm also new to docker.

I've made a simple custom image that installs PHP 7.3.

**Dockerfile**
```Dockerfile
FROM abstruse_builder

COPY init.sh /home/abstruse/init.sh

# Update environment
RUN sudo apt-get update -y && sudo apt-get upgrade -y

# Prepare PHP installation
RUN sudo apt-get install -y software-properties-common ca-certificates apt-transport-https
RUN sudo add-apt-repository -y ppa:ondrej/php

# Install PHP 7.3
RUN sudo apt-get install -y php7.3 php7.3-mysql php7.3-pdo php7.3-mbstring php7.3-zip php7.3-dom
```

**init.sh**
```sh
# giving docker access to abstruse user
if [ -e /var/run/docker.sock ]; then
  sudo chown -R 1000:100 /var/run/docker.sock > /dev/null 2>&1
fi
```

**.abstruse.yml**
```yml
image: laravel

before_install:
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php --file-name=composer
  - php -r "unlink('composer-setup.php');"

install:
  - composer install --no-interaction
  - composer 
```

Pushing to the github repo works and it detects that, but somehow the build instantly gets marked as successful without providing any more information, not even a log.
I've seen that there is a list of images that were used to build, but there are no images listed. Also the build time is 00:00 on each build.

I already tried to switch between the abstruse_builder and my custom build, but nothing fixed that problem.

I'm new into CI and couldn't find any similar problems here.

Thanks!
