### ISSUE TITLE
How can i fix this? 👍🏻 

### ISSUE THREAD

**Issue by pyalpha** [bleenco/abstruse#518]
![grafik](https://user-images.githubusercontent.com/40123243/120030209-7672e280-bff7-11eb-9a8d-ab389abdc0ee.png)

**Comment by pyalpha** [comment]
my `.abstruse.yml` :
```yml
image: bitnami:node
script:
    - node --version
```
What am I doing wrong?
