### ISSUE TITLE
Prepare image before running a script.

### ISSUE THREAD

**Issue by MrCyjaneK** [bleenco/abstruse#537]
It would be nice to have an option to prepare image inside od the `.abstruse.yml` file

```yaml
prepare:
  image: debian:latest // Source image
  TTL: 24 days // When image should be deleted and created again
  commands:
    - apt update
    - apt install neofetch
script:
  - neofetch
```
That option would allow us to save a lot of network and time on builds that download something from the `apt` repository, without the need to prepare the image manually.
