### ISSUE TITLE
Cache is being used always

### ISSUE THREAD

**Issue by MrCyjaneK** [bleenco/abstruse#550]
Cache seems to be used everytime, even when no `cache:` is provided.
![image](https://user-images.githubusercontent.com/20381330/123551066-7ab62b00-d770-11eb-9659-16ba7fe76514.png)

while the config is:

```yaml
image: golang:buster
script:
  - ./build.sh before
  - ./build.sh build
```

note: I may have used `cache:` once, in the `.abstruse.yml` in some previous job.
